version: "3.8"
services:
  backend:
    build: ./fast-api-backend
    env_file:
      - ./fast-api-backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./fast-api-backend:/app
    restart: always

  frontend:
    build: ./fast-api-frontend
    env_file:
      - ./fast-api-frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
